apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend-to-public-api
spec:
  destination:
    name: public-api
    partition: ecs
  sources:
    - name: frontend
      partition: eks
      action: allow